### ISSUE TITLE
Failure in PublishFrame codec 

### ISSUE THREAD

**Issue by cridmann** [fcabestre/Scala-MQTT-client#4]
Hello - this one may be tricky to track down.

I am getting a scodec decode error on certain inputs for the `PublishFrame`:

```
[error] a.a.OneForOneStrategy - PublishFrame: cannot acquire 50920 bits from a vector that contains 46312 bits
java.lang.IllegalArgumentException: PublishFrame: cannot acquire 50920 bits from a vector that contains 46312 bits
	at scodec.Decoder$$anonfun$decodeValidValue$1.apply(Decoder.scala:54) ~[scodec-core_2.11-1.6.0.jar:na]
	at scodec.Decoder$$anonfun$decodeValidValue$1.apply(Decoder.scala:54) ~[scodec-core_2.11-1.6.0.jar:na]
	at scalaz.$bslash$div.valueOr(Either.scala:214) ~[scalaz-core_2.11-7.1.0.jar:na]
	at scodec.Decoder$class.decodeValidValue(Decoder.scala:54) ~[scodec-core_2.11-1.6.0.jar:na]
	at scodec.Codec$$anon$1.decodeValidValue(Codec.scala:216) ~[scodec-core_2.11-1.6.0.jar:na]
[error] a.a.OneForOneStrategy - PublishFrame: cannot acquire 50920 bits from a vector that contains 46312 bits
java.lang.IllegalArgumentException: PublishFrame: cannot acquire 50920 bits from a vector that contains 46312 bits
	at scodec.Decoder$$anonfun$decodeValidValue$1.apply(Decoder.scala:54) ~[scodec-core_2.11-1.6.0.jar:na]
	at scodec.Decoder$$anonfun$decodeValidValue$1.apply(Decoder.scala:54) ~[scodec-core_2.11-1.6.0.jar:na]
	at scalaz.$bslash$div.valueOr(Either.scala:214) ~[scalaz-core_2.11-7.1.0.jar:na]
	at scodec.Decoder$class.decodeValidValue(Decoder.scala:54) ~[scodec-core_2.11-1.6.0.jar:na]
	at scodec.Codec$$anon$1.decodeValidValue(Codec.scala:216) ~[scodec-core_2.11-1.6.0.jar:na]
```

Perhaps there is a bug in `RemainingLengthCodec` ?

Also note: this exception will bubble up to the supervisor strategy of the actor that created the `Manager`, and it leaves the client of this API in charge of restarting the actor/connection if they want it.  This is probably OK, but just wanted to make sure you were aware.  Perhaps an improvement is to override the `preRestart` hook to maintain the MQTT connection if the client chooses that this exception is OK.

**Comment by fcabestre** [comment]
About the second point, I've recently realised that when a decoding error occurs, the MQTT specification expects the client just to shut down the connection ! At least this is explicitly said in the [3.1.1 specification](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718110). 

So in the ```0.6-SNAPSHOT```, I have enforced this rule and a corollary : when reconnecting with ```clean session``` unset, all in flight QoS 1 and 2 messages are resent with the ```dup``` flag set.

I have some cleaning up to perform, try to fix your main decoding issue and I'll release a ```0.6``` to maven central.

**Comment by fcabestre** [comment]
What would be just amazing to help me understand this issue, is if you could provide a ```Wireshark``` or ```tcpdump``` capture of packets containing the culprit. By the way, I will try to round trip the 50920 and 46312 values through the remaining length codec just to see...

**Comment by cridmann** [comment]
I've tried doing those bytes as well, and I've provided another test for large messages here:

https://github.com/cridmann/Scala-MQTT-client/commit/e9eee4be6fe5eb7add93ec10b081ba2588d9900d

I'm not sure if that proves anything.  But perhaps maybe the bug is with the different protocol versions.  I'll have to confirm, but maybe my broker is understanding version 3.1 and this client only does 3.0?

**Comment by fcabestre** [comment]
The Scala client is based on version 3.1 (or at least should be :smile:). I'm planing to incorporate 3.1.1 in a later release as this is the current version of MQTT in the new OASIS governance. What broker are your client talking to ?

**Comment by fcabestre** [comment]
I've started investigating with the example you sent. The remaining length in this frame is provided by the two bytes ```-125 50``` (```0x83 0x32``` in hexadecimal). I've applied the specification's decoding  algorithm by hand finding a length of ```6403```. 

At the ```sbt``` console I've then played with the remaining length codec with these value and found it correct. This is evidence that it is not our suspect. 

I will now investigate with the remaining of the frame... stay tuned :smiley:

**Comment by cridmann** [comment]
My clients are talking to IBM's MessageSight broker, which looking around I think they are in fact using MQTT version 3.1 so it shouldn't be a problem.  Furthermore, it seems that 3.1.1 is backwards compatible with 3.1 so I don't think it would be an issue as I suspected earlier.

My scenario involved publishing a message to MessageSight over JMS, and consuming the message over MQTT (the broker handles protocol translations).  This has worked for every message I have thrown at it except this one.

I can take a crack at the manual decode too sometime today or tomorrow.  If we can't find the culprit, perhaps I can plug in Paho's MQTT client to see how it fares.

**Comment by cridmann** [comment]
OK from my latest experiments, it seems that I can reliably reproduce this on the broker that I'm using.

For a large message that I publish with your `LocalPublisher`, the `LocalSubscriber` will receive `n` messages to complete 1 MQTT frame (where `n` depends on the size of the published payload).  

On my setup, the tipping point was a publish payload of anything greater than 5772 bytes, which is of course greater than the max TCP packet (1448 on my wireshark).  So akka-IO only appears to be buffering a subset of the entire MQTT frame?  

Please see this commit for an example: https://github.com/cridmann/Scala-MQTT-client/commit/a875fe53ed6f27d3e20f594bdd54944dff52baa4

Also I've committed a log file that shows this behavior:  https://github.com/cridmann/Scala-MQTT-client/commit/5369112ea56519f0a7ab9b83661b116c29b40c39   

Note that the second message received is `unhandled` as the `Engine.scala` will disconnect on the decode error as shown in the original post.

I'd be interested if you are able to reproduce this using your broker.  When I swapped out my broker with HiveMQ, the problem appeared to go away.  However, to make things more confusing, I then swapped in my original broker and used Paho's MQTT client and the problem went away as well.

**Comment by fcabestre** [comment]
Mmmm... Weird! I've added an integration test (runable with ```sbt it:test```) which basically round trips a random 65535 bytes message though my local ```mosquitto``` broker. It runs without problem even while ```Wireshark``` tells me about a *full TCP window*. But as all is local to my machine, the packets go through ```lo``` instead of ```eth0``` which may hide another wrong behaviour. 

Still investigating...

**Comment by cridmann** [comment]
Hmm I think you hit on to something there comparing `localhost` and `eth0`.  Your integration tests passed for me on my local hiveMQ, but they fail when I put the broker on a remote server.  The test fails with the same behavior I have seen for my own scenarios.

I also tried playing around with some of the akka-io configs:

```
    "akka.io.tcp.batch-accept-limit": "10",
    "akka.io.tcp.direct-buffer-pool-limit": "1000",
    "akka.io.tcp.direct-buffer-size": "128 KiB",
    "akka.io.tcp.file-io-dispatcher": "akka.actor.default-dispatcher",
    "akka.io.tcp.file-io-transferTo-limit": "512 KiB",
    "akka.io.tcp.finish-connect-retries": "5",
    "akka.io.tcp.management-dispatcher": "akka.actor.default-dispatcher",
    "akka.io.tcp.max-channels": "256000",
    "akka.io.tcp.max-received-message-size": "unlimited",
    "akka.io.tcp.nr-of-selectors": "1",
    "akka.io.tcp.register-timeout": "5s",
    "akka.io.tcp.selector-association-retries": "10",
    "akka.io.tcp.selector-dispatcher": "akka.io.pinned-dispatcher",
    "akka.io.tcp.trace-logging": "off",
    "akka.io.tcp.windows-connection-abort-workaround-enabled": "auto",
    "akka.io.tcp.worker-dispatcher": "akka.actor.default-dispatcher",
```

Changing these settings appeared to have no effect.

Perhaps this is worth bringing up in the akka mailing list?

**Comment by fcabestre** [comment]
The fact is that I've reproduced the issue on ```lo``` with a message big enough (65535 bytes was not enough!). Its obviously related to the size of the TCP buffers. The truth is that I'm suspecting I should have implemented flow control with ```Akka IO```. It's of course planned, but I didn't imagine to be bitten by this beast yet ;-). I'm pretty sure this is the way to go...

I will be busy this week attending the [Devoxx France](http://www.devoxx.fr) conference. I'll have a look to this probably by this week end.

**Comment by cridmann** [comment]
Ah a red herring indeed - it didn't occur to me that the buffer size is different from each network interface on the same OS.

I did a real quick and dirty commit which solved the issue for me and seems to pass all of your tests/integration tests.  I wasn't anticipating creating a PR for this, as I figured it would get refactored away once we use the APIs akka-io provides for flow control.

Anyways, if you're interested here is the commit:  https://github.com/cridmann/Scala-MQTT-client/commit/ac2d8c43ea70784ba9da216a58c5bb72aba5dcd2

Enjoy the conference - looks like some good presenters!

**Comment by fcabestre** [comment]
Hi,

Sorry to react so lately. Yes, you've got it, that's the way to handle the problem. The truth is I was mistaken: this is not a flow control issue, It's far more trivial and I've completely overlooked it. What ```Received``` provides us is a chunk of data with no guaranties of any mapping to a ```Frame```. In your case there is not enough bytes because of the receive buffer size. But there can be more bytes than required for just one ```Frame```. And with my current code I will miss them! 

I'm looking a way to implement that in an elegant way, using ```scodec-stream``` maybe. Or I will have to reconsider the codecs, generalizing your solution, splitting them in a header + size part and a payload part, and reconsidering how received bytes are handled.

Anyway, thanks for your help... And indeed the conference was really great :smiley:
