### ISSUE TITLE
Support both Scala 2.11 & 2.12

### ISSUE THREAD

**Issue by fcabestre** [fcabestre/Scala-MQTT-client#9]

**Comment by francisdb** [comment]
Everything is documented here.
http://www.scala-sbt.org/0.13/docs/Cross-Build.html

If there is no specific 2.11/2.12 only code it should boil down to adding this in the build file

```scala
crossScalaVersions := Seq("2.8.2", "2.9.2", "2.10.0")
```

and prefixing release/build commands with `+`

**Comment by fcabestre** [comment]
Yes, I've already seen this material. The fact is that I use `project/Build.scala` instead of the classical (and now probably preferred) `build.sbt`. And I've failed in this configuration. Now I've just tried more successfully to add a minimal `build.sbt` with the required information. This suggests I will change to a full `build.sbt` based build to resolve this issue.

**Comment by fcabestre** [comment]
After some wandering through the winding of `build.sbt`, I've finally achieved a cross Scala versions build. It's at least available on the OSS Nexus Repository Manager with version `0.7.0-SNAPHOT` while waiting for a true reactivation of this project!
